env:
  - DOCKER_COMPOSE_VERSION: 1.9.0
sudo: required
services: docker
before_install: 
  - docker-compose up -d
  - docker-compose exec web rake db:create
script:
  - docker-compose exec bitcoin-adapter rspec --format doc --fail-fast --color
  - docker-compose exec web rspec --format doc --fail-fast
