default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  url: postgresql://db
  database: skeemclub_development
  username: skeemclub
  password: password

test:
  <<: *default
  url: postgresql://db
  database: skeemclub_test
  username: skeemclub
  password: password

production:
  <<: *default
  url: postgresql://db
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
