default: &default
  entry_fee: '0.015'
  nocode_fee: '0.015'
  confirmations: 3
  host: 'bitcoin-adapter'
  port: '4567'
  user: 'user'
  password: 'password'

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
