default: &default
  entry_fee: '0.015'
  confirmations: 3
  server:
    host: 'localhost'
    port: 8332
    user: 'user'
    password: 'password'

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
