#!/usr/bin/env bash
VERSION="0.13.1"
FILENAME="bitcoin-${VERSION}-x86_64-linux-gnu.tar.gz"
USER="user"
PASSWORD="password"

wget "https://bitcoin.org/bin/bitcoin-core-0.13.1/$FILENAME" -O "/tmp/$FILENAME"
tar -xvf "/tmp/$FILENAME" -C "/tmp"

mkdir -p /tmp/bin
ln -s "/tmp/bitcoin-${VERSION}/bin/bitcoin-cli" /tmp/bin/

export PATH=$PATH:"/tmp/bitcoin-${VERSION}/bin/"

#echo generating initial blocks
#bitcoin-cli -rpcuser=$USER -rpcpassword=$PASSWORD generate 101

echo starting bitcoin adapter server
cd bitcoin
pwd
bundle show sinatra
bundle install --gemfile=./Gemfile
bundle show sinatra
ruby server.rb

until curl user:password@localhost:4567/info
do
	sleep 1
done
