#!/usr/bin/env bash
VERSION="0.13.1"
FILENAME="bitcoin-${VERSION}-x86_64-linux-gnu.tar.gz"

wget "https://bitcoin.org/bin/bitcoin-core-0.13.1/$FILENAME" -O "/tmp/$FILENAME"
tar -xvf "/tmp/$FILENAME" -C "/tmp"

export PATH=$PATH:"/tmp/bitcoin-${VERSION}/bin/"

echo starting bitcoind
bitcoind -rpcport=8332 -rpcuser=user -rpcpassword=password -regtest -daemon

sleep 3

echo generating initial blocks
bitcoin-cli -rpcuser=user -rpcpassword=password generate 101
