driver: 'bitcoind'
sync_frequency: 1
user: 'user'
password: 'password'

redis:
  port: 10101

bitcoind:
  host: 'localhost'
  port: 8332
  user: 'user'
  password: 'password'
  account: 'payments'
  params: '-regtest'

electrum:
  host: 'localhost'
  port: 7777

mock:
